const businesses = [
    {
      businessName: "Example Business",
      businessId: "@businessexample1",
      category: "Entertainment",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexamle2",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
          {
      businessName: "Example Business",
      businessId: "@businessexample3",
      category: "Home/Decor",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample4",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample5",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample7",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample8",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample9",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample10",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample11",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample12",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample13",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample14",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample15",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample16",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample17",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample18",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample19",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample20",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample21",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample22",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
    {
      businessName: "Example Business",
      businessId: "@businessexample23",
      category: "Food & Drink",
      rating: 4.5,
      distance: "1.5 miles",
      bio: "The sun was setting over the horizon, painting the sky with a mix of oranges, pinks and purples. The air was still, with only the occasional chirping of crickets breaking the silence. Emily sat on the porch of her cottage, lost in thought. She had always loved this time of day, when the world seemed to slow down and all her worries melted away. She took a deep breath, savoring the sweet scent of blooming flowers that surrounded her. For a moment, everything was perfect.",
    },
  ];

export default businesses;